# Generated by Django 5.2.17 on 2026-08-08 01:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageInspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('auteur', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème principal')),
                ('mois_annee', models.CharField(max_length=50, verbose_name='Mois et Année (ex: Août 2026)')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Programme du mois en cours')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
            },
        ),
        migrations.CreateModel(
            name='EspacePersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectifs', models.TextField(blank=True, null=True, verbose_name='Mes objectifs')),
                ('vision', models.TextField(blank=True, null=True, verbose_name='Ma vision de vie')),
                ('qualites', models.TextField(blank=True, null=True, verbose_name='Mes qualités')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='espace_personnel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoteEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('espace_personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.espacepersonnel')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(verbose_name='Semaine N°')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème de la semaine')),
                ('objectif', models.CharField(max_length=255)),
                ('questions', models.TextField(help_text='Séparez les questions par un saut de ligne.', verbose_name='Questions de réflexion (une par ligne)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Semaine en cours')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semaines', to='core.programme')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Defi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('semaine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defi', to='core.semaine')),
            ],
        ),
        migrations.CreateModel(
            name='StatutDefi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('none', 'Non commencé'), ('started', "J'ai commencé"), ('completed', "J'ai terminé")], default='none', max_length=20)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts_utilisateurs', to='core.defi')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts_defis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'defi')},
            },
        ),
    ]
