# Generated by Django 5.2.17 on 2026-08-08 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semaine',
            options={'ordering': ['date_rendez_vous']},
        ),
        migrations.RemoveField(
            model_name='semaine',
            name='is_active',
        ),
        migrations.AddField(
            model_name='semaine',
            name='date_rendez_vous',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du mercredi'),
        ),
    ]
