# Generated by Django 5.2.17 on 2026-08-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil'),
        ),
    ]
