# Generated by Django 5.2.17 on 2026-08-11 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profil_photo_profil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='theme_couleur',
            field=models.CharField(choices=[('bleu_or', 'Bleu & Or'), ('violet_or', 'Violet & Or'), ('sombre', 'Sombre')], default='bleu_or', max_length=20, verbose_name='Thème de couleurs'),
        ),
        migrations.AddField(
            model_name='profil',
            name='xp_total',
            field=models.PositiveIntegerField(default=0, verbose_name='XP'),
        ),
        migrations.AddField(
            model_name='statutdefi',
            name='preuve_photo',
            field=models.ImageField(blank=True, null=True, upload_to='preuves/', verbose_name='Photo preuve'),
        ),
        migrations.AddField(
            model_name='statutdefi',
            name='xp_defi_accorde',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statutdefi',
            name='xp_photo_accorde',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('pro', 'Ma vie professionnelle / mes études'), ('argent', 'Mon argent'), ('objectifs', 'Mes objectifs'), ('moi', 'Moi-même'), ('reseaux', 'Réseaux sociaux'), ('entourage', 'Mon entourage')], max_length=20)),
                ('texte', models.CharField(max_length=255, verbose_name='Action proposée')),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.defi')),
            ],
            options={
                'ordering': ['categorie', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PratiqueSpirituelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('materiel', models.CharField(max_length=255, verbose_name='Matériel')),
                ('moment', models.CharField(max_length=255, verbose_name='Moment')),
                ('impact', models.CharField(max_length=255, verbose_name='Impact')),
                ('defi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratiques', to='core.defi')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminee', models.BooleanField(default=False)),
                ('preuve_photo', models.ImageField(blank=True, null=True, upload_to='preuves/', verbose_name='Photo preuve')),
                ('xp_photo_accorde', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_utilisateurs', to='core.action')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_choisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'action')},
            },
        ),
        migrations.CreateModel(
            name='PratiqueUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faite', models.BooleanField(default=False)),
                ('pratique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='core.pratiquespirituelle')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratiques_faites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'pratique')},
            },
        ),
    ]
