# Generated by Django 5.2.17 on 2026-08-11 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profil_theme_couleur_profil_xp_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='categorie',
            field=models.CharField(choices=[('pro', 'Ma vie professionnelle / mes études'), ('argent', 'Mon argent'), ('objectifs', 'Mes objectifs'), ('moi', 'Moi-même'), ('reseaux', 'Réseaux sociaux'), ('entourage', 'Mon entourage'), ('spiritualite', 'Spiritualité')], max_length=20),
        ),
        migrations.CreateModel(
            name='EngagementDefi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('pro', 'Ma vie professionnelle / mes études'), ('argent', 'Mon argent'), ('objectifs', 'Mes objectifs'), ('moi', 'Moi-même'), ('reseaux', 'Réseaux sociaux'), ('entourage', 'Mon entourage'), ('spiritualite', 'Spiritualité')], max_length=20)),
                ('action_personnelle', models.TextField(verbose_name='Quelle action vas-tu réaliser ?')),
                ('date_prevue', models.CharField(max_length=100, verbose_name='Quand vas-tu la réaliser ?')),
                ('critere_validation', models.TextField(verbose_name='Comment sauras-tu que ton défi est terminé ?')),
                ('statut', models.CharField(choices=[('none', 'Non commencé'), ('engaged', 'Engagement pris'), ('completed', 'Terminé')], default='engaged', max_length=20)),
                ('preuve_fichier', models.ImageField(blank=True, null=True, upload_to='preuves_engagements/', verbose_name='Preuve (photo)')),
                ('preuve_texte', models.TextField(blank=True, null=True, verbose_name='Preuve (texte)')),
                ('xp_engagement_accorde', models.BooleanField(default=False)),
                ('xp_termine_accorde', models.BooleanField(default=False)),
                ('xp_preuve_accorde', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='core.semaine')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements_defis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'semaine', 'categorie')},
            },
        ),
    ]
