# Generated by Django 5.2.17 on 2026-08-11 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_action_categorie_engagementdefi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('pro', 'Ma vie professionnelle / mes études'), ('argent', 'Mon argent'), ('objectifs', 'Mes objectifs'), ('moi', 'Moi-même'), ('reseaux', 'Réseaux sociaux'), ('entourage', 'Mon entourage'), ('spiritualite', 'Spiritualité')], max_length=20)),
                ('texte', models.TextField(verbose_name='Mission')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.semaine')),
            ],
        ),
        migrations.CreateModel(
            name='MissionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('none', 'À faire'), ('engaged', 'En cours'), ('completed', 'Réalisé')], default='none', max_length=20)),
                ('preuve_fichier', models.ImageField(blank=True, null=True, upload_to='preuves_missions/', verbose_name='Preuve (photo)')),
                ('preuve_texte', models.TextField(blank=True, null=True, verbose_name='Preuve (texte)')),
                ('xp_engagement_accorde', models.BooleanField(default=False)),
                ('xp_termine_accorde', models.BooleanField(default=False)),
                ('xp_preuve_accorde', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_utilisateurs', to='core.missionsemaine')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_choisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'mission')},
            },
        ),
        migrations.DeleteModel(
            name='EngagementDefi',
        ),
    ]
