# Generated by Django 5.2.17 on 2026-08-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_missionsemaine_missionutilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='categorie',
            field=models.CharField(choices=[('pro', 'Ma vie professionnelle / mes études'), ('argent', 'Mon argent'), ('objectifs', 'Mes objectifs'), ('moi', 'Moi-même'), ('reseaux', 'Réseaux sociaux'), ('spiritualite', 'Spiritualité')], max_length=20),
        ),
        migrations.AlterField(
            model_name='missionsemaine',
            name='categorie',
            field=models.CharField(choices=[('pro', 'Ma vie professionnelle / mes études'), ('argent', 'Mon argent'), ('objectifs', 'Mes objectifs'), ('moi', 'Moi-même'), ('reseaux', 'Réseaux sociaux'), ('spiritualite', 'Spiritualité')], max_length=20),
        ),
    ]
