# Generated by Django 5.2.17 on 2026-08-11 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_action_categorie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='missionutilisateur',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='missionutilisateur',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='missionutilisateur',
            name='utilisateur',
        ),
        migrations.CreateModel(
            name='DomaineSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('pro', 'Ma vie professionnelle / mes études'), ('argent', 'Mon argent'), ('objectifs', 'Mes objectifs'), ('moi', 'Moi-même'), ('reseaux', 'Réseaux sociaux'), ('spiritualite', 'Spiritualité')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('pourquoi_ca_compte', models.TextField(blank=True, null=True)),
                ('semaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines', to='core.semaine')),
            ],
        ),
        migrations.CreateModel(
            name='ActionProposee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.domainesemaine')),
            ],
        ),
        migrations.CreateModel(
            name='DomaineUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('none', 'À faire'), ('engaged', 'En cours'), ('completed', 'Réalisé')], default='none', max_length=20)),
                ('donnees_action', models.JSONField(blank=True, null=True, verbose_name='Données interactives du flux')),
                ('preuve_fichier', models.ImageField(blank=True, null=True, upload_to='preuves_domaines/')),
                ('preuve_texte', models.TextField(blank=True, null=True)),
                ('xp_gagnes', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('action_choisie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.actionproposee')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix_utilisateurs', to='core.domainesemaine')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaines_choisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'domaine')},
            },
        ),
        migrations.DeleteModel(
            name='MissionSemaine',
        ),
        migrations.DeleteModel(
            name='MissionUtilisateur',
        ),
    ]
