# Generated by Django 5.2.17 on 2026-08-11 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_missionutilisateur_mission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionBonusUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('none', 'À faire'), ('engaged', 'En cours'), ('completed', 'Réalisé')], default='engaged', max_length=20)),
                ('donnees_action', models.JSONField(blank=True, null=True)),
                ('preuve_fichier', models.ImageField(blank=True, null=True, upload_to='preuves_domaines/')),
                ('preuve_texte', models.TextField(blank=True, null=True)),
                ('xp_gagnes', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('action_choisie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actionproposee')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_utilisateurs', to='core.domainesemaine')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_bonus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilisateur', 'action_choisie')},
            },
        ),
    ]
