# Generated by Django 5.2.17 on 2026-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_actionbonusutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='mois_annee',
        ),
        migrations.AddField(
            model_name='programme',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='programme',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='programme',
            name='statut',
            field=models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('archive', 'Précédent / Archive')], default='a_venir', max_length=20),
        ),
        migrations.AlterField(
            model_name='action',
            name='categorie',
            field=models.CharField(choices=[('pro', 'Ma vie professionnelle / mes études'), ('argent', 'Mon argent'), ('objectifs', 'Mes objectifs'), ('moi', 'Moi-même'), ('reseaux', 'Réseaux sociaux'), ('amour', 'Relation amoureuse'), ('spiritualite', 'Spiritualité')], max_length=20),
        ),
        migrations.AlterField(
            model_name='domainesemaine',
            name='categorie',
            field=models.CharField(choices=[('pro', 'Ma vie professionnelle / mes études'), ('argent', 'Mon argent'), ('objectifs', 'Mes objectifs'), ('moi', 'Moi-même'), ('reseaux', 'Réseaux sociaux'), ('amour', 'Relation amoureuse'), ('spiritualite', 'Spiritualité')], max_length=20),
        ),
    ]
