# Generated by Django 5.2.17 on 2026-08-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_programme_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteevolution',
            name='type_note',
            field=models.CharField(choices=[('libre', 'Note libre'), ('defi', 'Réflexion liée à un défi'), ('bilan', 'Bilan de semaine')], default='libre', max_length=20),
        ),
    ]
