# Generated by Django 5.2.17 on 2026-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_noteevolution_type_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='illustration',
            field=models.ImageField(blank=True, null=True, upload_to='programmes_illus/', verbose_name='Illustration (PNG/JPG)'),
        ),
        migrations.AddField(
            model_name='programme',
            name='ordre',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre de parcours'),
        ),
    ]
