# Generated by Django 5.2.17 on 2026-08-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_programme_illustration_programme_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='date_disponibilite',
            field=models.DateField(blank=True, null=True, verbose_name='Date de disponibilité'),
        ),
    ]
