# Generated by Django 5.2.17 on 2026-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_programme_date_disponibilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='publie',
            field=models.BooleanField(default=False, verbose_name='Publié'),
        ),
    ]
