# Generated by Django 5.2.17 on 2026-08-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_programme_publie'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='citation_personnelle',
            field=models.TextField(blank=True, null=True, verbose_name='Ma citation personnelle'),
        ),
    ]
