# Generated by Django 5.2.17 on 2026-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profil_citation_personnelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdhesionAurea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('age', models.PositiveIntegerField(verbose_name='Âge')),
                ('genre', models.CharField(choices=[('F', 'Femme'), ('M', 'Homme'), ('A', 'Autre')], max_length=10, verbose_name='Genre')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro WhatsApp')),
                ('destination_attribuee', models.CharField(blank=True, max_length=50, verbose_name='Destination attribuée')),
                ('code_testeuse_utilise', models.BooleanField(default=False, verbose_name='Code testeuse utilisé')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
            ],
            options={
                'verbose_name': 'Adhésion Auréa',
                'verbose_name_plural': 'Adhésions Auréa',
                'ordering': ['-date_demande'],
            },
        ),
    ]
